---! Enums & Types !---
create type user_role as enum (
    'guest',
    'talent',
    'external_client',
    'operations',
    'finance',
    'admin',
    'superadmin'
);
create type name_suffix as enum (
    'Sr.',
    'Jr.',
    'I',
    'II',
    'III',
    'IV',
    'V',
    'MD',
    'PhD',
    'JD',
    'DDS',
    'RN',
    'CPA',
    'Esq.'
);
---! Table Schema !---
create table profiles (
    --
    -- Required credentials
    -- 
    id uuid references auth.users on delete cascade primary key,
    role user_role not null default 'guest',
    --
    -- Names (Optional) 
    --
    first_name text check (first_name ~ '^[a-zA-Z\s''\-]+$'),
    middle_name text check (middle_name ~ '^[a-zA-Z\s''\-]+$'),
    last_name text check (last_name ~ '^[a-zA-Z\s''\-]+$'),
    suffix name_suffix,
    username text unique check (username ~ '^[a-zA-Z0-9._-]{1,20}$'),
    --
    -- Personal information (Optional)
    --
    phone text check (phone ~ '^\+?[0-9]{7,15}$'),
    birthday date,
    address_line1 text check (char_length(address_line1) <= 100),
    address_line2 text check (char_length(address_line2) <= 100),
    city text check (char_length(city) <= 100),
    province text check (char_length(province) <= 100),
    country text default 'Philippines' check (char_length(country) <= 100),
    bio text check (char_length(bio) <= 250),
    -- 
    -- Timestamps (Required, Autogenerated)
    -- 
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);
---! Functions & Triggers !---
create or replace function handle_new_user() returns trigger as $$ begin
insert into public.profiles (id)
values (new.id);
return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
after
insert on auth.users for each row execute procedure handle_new_user();
-- auto-update updated_at on any profile change
create or replace function set_updated_at() returns trigger as $$ begin new.updated_at = now();
return new;
end;
$$ language plpgsql;
create trigger profiles_updated_at before
update on profiles for each row execute procedure set_updated_at();