name: Next.js CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4                   # Checkout code
      - uses: actions/setup-node@v4                 # Setup Node 22 + Cache
        with:
          node-version: 22
          cache: 'pnpm'
      - uses: pnpm/action-setup@v3                  # Setup pnpm 9
        with:
          version: 9
      - id: pnpm-cache                              # Get pnpm store directory
        run: |
          STORE_PATH="$(pnpm store path)" 
          echo "pnpm store path: $STORE_PATH"
          echo "STORE_PATH=$STORE_PATH" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4                      # Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install --frozen-lockfile         # Install pnpm files & modules
      - run: pnpm tsc --noEmit                      # Check types in TypeScript
      - run: pnpm lint                              # Run linter
      - run: pnpm build                             # Build project
        # env:
        #   # Add mock ENVs if your build requires them to pass ???
        #   NEXT_PUBLIC_SUPABASE_URL: "http://localhost:54321"
        #   NEXT_PUBLIC_SUPABASE_ANON_KEY: "mock-key"